_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.0
            "6": 4.50.0.dev0
            "8":
                - 1
                - 5
            "12": 0.19.0
            "13": linux-x86_64
distance:
    value: euclidean
embedding_strategy:
    value: last_hidden_mean
model:
    value: OpenGVLab/InternVL3-2B
